### ISSUE TITLE
dotfiles

### ISSUE THREAD

**Issue by ghost** [uhnomoli/dots#1]
Sorry to contact you here on this way.
But I didn't find a other way.

Could you add to http://dotshare.it/ a section for 

panels
  - lemonbar

wms
  - cwm

thanks man

**Comment by uhnomoli** [comment]
Sorry for the late response, I've been quite busy.

For the time being I'm holding off on making any changes to DotShare as I am working on a complete overhaul of the website as mentioned in the latest news post.

With the overhaul, I'm not sure how or if existing submissions will be transferred over. Because of that, while trying to avoid putting the site into a read-only mode as I'm unsure of when the new version will be launched, I'm avoiding putting any work into the current site.

I hope you understand. Thanks for your interest in DotShare.
